Fix instrument name issues
nanaian/mamar pull request #30
Opened 2022-10-14 20:10 UTC by Wrymouth

That's all I got right now, this code is confusing...
Instruments should be consistently named/numbered now, with no duplicates.

2022-10-14 20:54 UTC, nanaian approved these changes
Need to merge this into web

2022-10-16 13:04 UTC, Wrymouth commented
Just completed the JSON instrument list, though there's a couple instruments where I'm not sure what category they belong in, categorized as "Unsure" for now.

2022-10-16 16:01 UTC, nanaian requested changes

2022-10-16 16:01 UTC, nanaian commented on mamar-web/src/app/instruments.ts
> +            { bank: 0x03, patch: 0x8B, name: "Accordion 3" },
Yes, put them there please!

2022-10-16 16:01 UTC, nanaian commented on mamar-web/src/app/instruments.ts
> +        name: "Unsure",
Can you name this "other"?

2022-10-16 16:01 UTC, nanaian commented on mamar-web/src/app/instruments.ts
> +            { bank: 0x03, patch: 0x99, name: "Cat [Lead 8 (bass + lead)]" },
Remove the part in square brackets; just call it cat meow or something

2022-10-16 16:22 UTC, merged